FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install

WORKDIR /app/packages/DB
RUN pnpm install
RUN pnpm prisma generate

WORKDIR /app/apps/http-server
RUN pnpm install
RUN pnpm run build

EXPOSE 3001
CMD ["pnpm", "start"]