FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install

WORKDIR /app/packages/DB
RUN pnpm install
RUN pnpm prisma generate

WORKDIR /app/apps/ws-server
RUN pnpm install
RUN pnpm run build
RUN ./dist/chatWorker.js

EXPOSE 8080
CMD ["pnpm", "start"]